In [147]:
import numpy as np
import pandas as pd

In [125]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa','profile_score','lpa'])

In [126]:
df

,cgpa,profile_score,lpa
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


In [148]:
def initialize_parameters(layers_dims):
    np.random.seed(3)
    parameters = {}
    L = len(layers_dims)            # number of layers in the network

    for l in range(1, L):
        parameters['W' + str(l)] = np.ones((layers_dims[l], layers_dims[l-1])) * 0.1
        parameters['b' + str(l)] = np.zeros((layers_dims[l], 1))
    return parameters

In [128]:
initialize_parameters([2, 2, 1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1, 0.1]]),
 'b2': array([[0.]])}

In [149]:
def linear_forward(A_prev, W, b):
    Z = np.dot(W, A_prev) + b
    return Z

In [150]:
def L_layer_forward(X, parameters):
    A = X
    L = len(parameters) // 2 

    for l in range(1, L+1):
        A_prev = A
        Wl = parameters['W'+ str(l)]
        bl = parameters['b'+ str(l)]
        # print("A"+str(l-1)+": ",A_prev)
        # print("W"+str(l)+": ",Wl)
        # print("b"+str(l)+": ",bl)
        # print("--"*20)

        A = linear_forward(A_prev, Wl, bl)
        # print("A"+str(l)+": ", A)

    return A, A_prev

In [151]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1)
y = df[['lpa']].values[0][0]

parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X, parameters)

In [152]:
# y_hat is now 2D array from forward pass (shape: 1,1)

In [154]:
def update_parameters(parameters, y, y_hat, A1, X):
    # Extract scalar from y_hat (2D array)
    y_hat_scalar = y_hat.item() if hasattr(y_hat, 'item') else y_hat[0][0]
    error = 0.001 * 2 * (y - y_hat_scalar)
    
    parameters['W2'][0][0] = parameters['W2'][0][0] + (error * A1[0][0]).item()
    parameters['W2'][0][1] = parameters['W2'][0][1] + (error * A1[1][0]).item()
    parameters['b2'][0][0] = parameters['b2'][0][0] + error
    
    parameters['W1'][0][0] = parameters['W1'][0][0] + (error * parameters['W2'][0][0] * X[0][0]).item()
    parameters['W1'][1][0] = parameters['W1'][1][0] + (error * parameters['W2'][0][0] * X[1][0]).item()
    parameters['b1'][0][0] = parameters['b1'][0][0] + (error * parameters['W2'][0][0]).item()
    
    parameters['W1'][0][1] = parameters['W1'][0][1] + (error * parameters['W2'][0][1] * X[0][0]).item()
    parameters['W1'][1][1] = parameters['W1'][1][1] + (error * parameters['W2'][0][1] * X[1][0]).item()      
    parameters['b1'][1][0] = parameters['b1'][1][0] + (error * parameters['W2'][0][1]).item()

In [134]:
update_parameters(parameters, y, y_hat,A1,X)

In [139]:
parameters

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1, 0.1]]),
 'b2': array([[0.]])}

In [140]:
X = df[['cgpa', 'profile_score']].values[2].reshape(2,1)
y = df[['lpa']].values[2][0]

y_hat,A1 = L_layer_forward(X, parameters)

In [155]:
# epochs implemenation

parameters = initialize_parameters([2,2,1])
epochs = 5

for i in range(epochs):
    loss = []

    for j in range(df.shape[0]):
        X = df[['cgpa', 'profile_score']].values[j].reshape(2,1)
        y = df[['lpa']].values[j][0]

        y_hat,A1 = L_layer_forward(X, parameters)
        loss.append((y - y_hat[0][0])**2)

        update_parameters(parameters, y, y_hat,A1,X)

        loss.append((y - y_hat[0][0])**2)

    print('Epoch: ', i+1, ' Loss: ', np.array(loss).mean())
parameters

Epoch:  1  Loss:  26.28249792398698
Epoch:  2  Loss:  19.438253848220803
Epoch:  3  Loss:  10.13987443582752
Epoch:  4  Loss:  3.385561305106485
Epoch:  5  Loss:  1.3198454128484565


{'W1': array([[0.273603  , 0.28787155],
        [0.3993222 , 0.42586102]]),
 'b1': array([[0.02885522],
        [0.03133223]]),
 'W2': array([[0.42574893, 0.50219328]]),
 'b2': array([[0.11841278]])}

==========================================================
# Now same code by using Keras
###             & TesnorFlow

In [166]:
df

,cgpa,profile_score,lpa
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


In [156]:
import tensorflow
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense

In [157]:
model = Sequential()
model.add(Dense(2, activation='linear', input_dim=2))
model.add(Dense(1, activation='linear'))

d:\VS Code\env\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [144]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [145]:
model.get_weights()

[array([[-0.81208134,  0.61732745],
        [ 0.19221354, -0.14601207]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.57933575],
        [-0.9546139 ]], dtype=float32),
 array([0.], dtype=float32)]

In [160]:
new_weights = [np.array([[0.1, 0.1],
        [0.1, 0.1]], dtype=np.float32), 
        np.array([0.0, 0.0], dtype=np.float32),
        np.array([[0.1],[0.1]], dtype=np.float32),
        np.array([0.], dtype=np.float32)]

In [161]:
model.set_weights(new_weights)

In [162]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [163]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error', optimizer=optimizer)

In [164]:
model.fit(df.iloc[:,0:-1].values, df['lpa'].values, epochs=75, verbose=1, batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - loss: 27.9111
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 27.5832 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 27.2448
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 26.9268 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 26.5680
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 26.1900
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 25.8634 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 25.4375
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 25.0555
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 24.6636
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 24.2612
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 23.8015
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 23.3763
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 22.9285
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 22.5031
Epoch 16/75
4/4 

In [165]:
model.get_weights()

[array([[0.37353626, 0.37353626],
        [0.36541998, 0.36541998]], dtype=float32),
 array([0.272173, 0.272173], dtype=float32),
 array([[0.37276655],
        [0.37276655]], dtype=float32),
 array([0.20465036], dtype=float32)]